id: coming_home
alias: Coming Home
trigger:
  platform: state
  entity_id: group.all_persons
  to: "home"

action:
  - service: homeassistant.turn_on
    entity_id:
      - light.dimmable_lights
      - group.my_switches
