id: coming_home
alias: Coming Home
trigger:
  platform: state
  entity_id: group.all_persons
  to: 'home'

action:
  - service: homeassistant.turn_on
    entity_id:
      - light.dimmable_lights
      ## All switches except Makeup Mirror
      - switch.bathroom_light
      - switch.basket_lamp


      # - switch.makeup_mirror
      - switch.sideboard_lamp
      # - switch.christmas_star
      # - switch.christmas_tree
