id: coming_home
alias: Coming Home
trigger:
  platform: state
  entity_id: group.all_devices
  to: 'home'
action:
  - service: homeassistant.turn_on
    entity_id: group.bedroom
  - service: homeassistant.turn_on
    entity_id: group.studio
  - service: homeassistant.turn_on
    entity_id: group.livingroom