id: leaving_home
alias: Leaving Home
trigger:
- platform: state
  entity_id: group.all_devices
  to: 'not_home'
action:
  - service: homeassistant.turn_off
    entity_id: group.all_lights
  - service: homeassistant.turn_off
    entity_id: group.all_switches