id: leaving_home
alias: Leaving Home
trigger:
- platform: state
  entity_id: group.all_persons
  to: 'not_home'
action:
  - service: homeassistant.turn_off
    entity_id: light.dimmable_lights
  - service: homeassistant.turn_off
    entity_id: group.my_switches

