  version: '2'
  services:
    homeassistant:
      container_name: home-assistant
      image: homeassistant/home-assistant
      volumes:
        - /home/mans/hass_config:/config
        - /etc/localtime:/etc/localtime:ro
        - /etc/letsencrypt/:/etc/letsencrypt/
      restart: always
      network_mode: host

