title: Trastvägen 10

background: var(--background-image)

custom_header:
  background: 'rgba(155, 155, 155, 0.2)'
  compact_mode: true
  button_text:
    options: '{{ hours24 }}:{{ minutesLZ }}'

resources:
  - url: /hacsfiles/custom-header/custom-header.js
    type: module
  - url: /hacsfiles/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
    type: module
  - url: /hacsfiles/group-card/group-card.js
    type: module
  - url: /local/custom-ui/room-card.js
    type: module
  - url: /hacsfiles/upcoming-media-card/upcoming-media-card.js
    type: module
  - url: /community_plugin/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
    type: module
  - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    type: module
 

excluded_entities:
  - weblink.router
views:
  - title: Home
    path: home
    type: horizontal-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: picture-entity
            image: /local/assets/agnes.jpg
            entity: person.agnes
            name: Agnes

          - type: picture-entity
            image: /local/assets/mans.jpg
            entity: person.mans
            name: Måns
      
      - type: entities
        title: Rooms
        show_header_toggle: true
        entities:
          - group.bedroom
          - group.livingroom
          - group.studio_lights
          - group.bathroom

      - type: custom:group-card
        card:
          type: entities
          title: Bedroom
        group: group.bedroom

      - type: custom:group-card
        card:
          type: entities
          title: Living Room
        group: group.livingroom

      - type: custom:group-card
        card:
          type: entities
          title: Bathroom
        group: group.bathroom

      - type: custom:room-card
        card:
          type: entities
          title: Studio
        group: group.studio
        area: Studio

      - type: custom:upcoming-media-card
        entity: sensor.plex_recently_added
        title: Recently Downloaded

      - type: custom:xiaomi-vacuum-card
        entity: vacuum.xiaomi_vacuum_cleaner
        name: Dusty
        vendor: xiaomi
        image: /local/assets/vacuum_dimmed.png
      
      - type: custom:mini-media-player
        entity: media_player.kitchen_speaker
        artwork: cover


      - type: custom:mini-media-player
        entity: media_player.echo
        artwork: cover
  
  - title: Development
