title: Trastvägen 10

resources:
  - url: /local/custom_ui/monster-card.js?v=1
    type: js
  - url: /local/custom_ui/test-card.js
    type: js

excluded_entities:
  - weblink.router
views:
  - title: Home
    path: home
    type: horizontal-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: picture-entity
            image: /local/assets/agnes.jpg
            entity: person.agnes
            name: Agnes

          - type: picture-entity
            image: /local/assets/mans.jpg
            entity: person.mans
            name: Måns
      
      - type: entities
        title: Rooms
        show_header_toggle: true
        entities:
          - group.bedroom
          - group.livingroom
          - group.studio

      - type: entities
        title: Lights
        show_header_toggle: true
        entities:
          - light.living_room
          - light.mans_bedside_lamp
          - light.agnes_bedside_lamp
          - light.bedroom
          - light.studio

      - type: entities
        title: Switches
        show_header_toggle: true
        entities:
          - switch.switch_1
          - switch.painting_lamp_2
          - switch.christmas_star
          - switch.night_light
          - switch.balcony