title: Trastvägen 10

background: var(--background-image)

custom_header:
  background: 'rgba(155, 155, 155, 0.25)'
  compact_mode: true
  button_text:
    options: '{{ hours24 }}:{{ minutesLZ }}'

resources:
    - url: /hacsfiles/custom-header/custom-header.js
      type: module
    - url: /hacsfiles/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
      type: module
 

excluded_entities:
  - weblink.router
views:
  - title: Home
    path: home
    type: horizontal-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: picture-entity
            image: /local/assets/agnes.jpg
            entity: person.agnes
            name: Agnes

          - type: picture-entity
            image: /local/assets/mans.jpg
            entity: person.mans
            name: Måns
      
      - type: entities
        title: Rooms
        show_header_toggle: true
        entities:
          - group.bedroom
          - group.livingroom
          - group.studio

      - type: entities
        title: Lights
        show_header_toggle: true
        entities:
          # - light.living_room
          - light.mans_bedside_lamp
          - light.agnes_bedside_lamp
          - light.bedroom
          - light.studio

      - type: entities
        title: Switches
        show_header_toggle: true
        entities:
          - switch.painting_lamp_2