title: Trastvägen 10
# Exclude entities from "Unused entities" view

resources:
  - url: /local/custom_ui/monster-card.js?v=1
    type: js
  - url: /local/custom_ui/test-card.js
    type: js

excluded_entities:
  - weblink.router
views:
  - title: Home
    path: home
    type: horizontal-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: picture-entity
            image: /local/assets/agnes.jpg
            entity: person.agnes
            name: Agnes

          - type: picture-entity
            image: /local/assets/mans.jpg
            entity: person.mans
            name: Måns
      
      - type: entities
        title: Lights
        show_header_toggle: true
        entities:
          - light.living_room
          - light.mans_bedside_lamp
          - light.bedroom
          - light.studio
          - type: divider
          - light.night_light
          - switch.makeup_mirror
          - switch.painting_lamp
