id: agnes_bedside_flic_toggle
alias: "Agnes Bedside Flic toggle"
trigger:
  - platform: event
    event_type: flic_click
    event_data:
      button_name: flic_80e4da74ecfc
      click_type: double
action:
  - service: light.toggle
    data_template:
      entity_id: light.agnes_bedside_lamp 
