id: toggle_makeup_mirror
alias: "Toggle makeup mirror"
trigger:
  - platform: event
    event_type: flic_click
    event_data:
      button_name: flic_80e4da74e95c
      click_type: single
action:
  - service: switch.toggle
    entity_id: switch.switch_1

