id: test_flic
alias: "test flic"
trigger:
  - platform: event
    event_type: flic_click
    event_data:
      button_name: flic_80e4da74cd95
      click_tyoe: single
action:
  - service: light.toggle
    entity_id: light.living_room
