id: test_flic
alias: "test flic"
trigger:
  - platform: event
    event_type: flic_click
    event_data:
      button_name: flic_80e4da74d499
      click_tyoe: single
action:
  - service: switch.toggle
    entity_id: switch.makeup_mirror
