id: vacation_lights_off
alias: Vacation Script - Turn of the lights again
trigger:
  platform: time
  at: "22:00:00"
action:
  - alias: Turn of the lights again
    service: light.turn_off
    data:
      entity_id:
        - light.agnes_bedside_lamp
        - light.mans_bedside_lamp
        - light.living_room_lamp_1
        - light.living_room_lamp_2
        - light.studio_lamp
        - switch.basket_lamp
        - switch.sideboard_lamp
        - light.kitchen_ceiling
