id: toggle_bathroom
alias: "Toggle bathroom"
trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: 'toggle_bathroom'
action:
  - service: switch.toggle
    entity_id: switch.painting_lamp_2


