id: double_tap
alias: 'Cube double tap'
initial_state: true
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: mi_magic_cube_2
condition:
  condition: template
  value_template: >
    {% set valid_events = [1001, 2002, 3003, 4004, 5005, 6006] %}
    {{ trigger.event.data.event in valid_events }}
action:
  - service: automation.trigger
    data:
      entity_id: >
        {% if is_state('input_boolean.is_cube_double_tapped', 'on') %}
          automation.leaving_home
        {% else %}
          automation.coming_home
        {% endif %}
  - service: input_boolean.toggle
    target:
      entity_id: input_boolean.is_cube_double_tapped
