id: sundown
alias: Sundown
trigger:
  platform: sun
  event: sunrise
  offset: "+00:30:00"
action:
  - service: homeassistant.turn_off
    entity_id: switch.christmas_star
  - service: homeassistant.turn_off
    entity_id: switch.balcony