id: sunrise
alias: Sunrise
trigger:
  platform: sun
  event: sunset
  offset: "+00:00:00"
action:
  - service: homeassistant.turn_off
    entity_id: switch.christmas_star
  - service: homeassistant.turn_off
    entity_id: switch.balcony

