## All Lights
- platform: group
  name: "Dimmable Lights"
  entities:
    - light.living_room_lamp_1
    - light.living_room_lamp_2
    - light.living_room_ceiling

    - light.studio_lamp
    - light.studio_ceiling

    - light.mans_bedside_lamp
    - light.agnes_bedside_lamp
    - light.bedroom_ceiling

    - light.hallway_ceiling_1
    - light.hallway_ceiling_2

    - light.kitchen_ceiling

## Living room
- platform: group
  name: "Living Room Lights"
  entities:
    - light.living_room_lamp_1
    - light.living_room_lamp_2
    - light.living_room_ceiling

## Studio
- platform: group
  name: "Studio Lights"
  entities:
    - light.studio_lamp
    - light.studio_ceiling

## Bedroom
- platform: group
  name: "Bedroom Lights"
  entities:
    - light.mans_bedside_lamp
    - light.agnes_bedside_lamp
    - light.bedroom_ceiling

## Hallway
- platform: group
  name: "Hallway Lights"
  entities:
    - light.hallway_ceiling_1
    - light.hallway_ceiling_2

## Kitchen
- platform: group
  name: "Kitchen Lights"
  entities:
    - light.kitchen_ceiling

## Ceiling lights
- platform: group
  name: "Ceiling lights"
  entities:
    - light.kitchen_ceiling
    - light.hallway_ceiling_1
    - light.hallway_ceiling_2
    - light.bedroom_ceiling
    - light.living_room_ceiling
    - light.studio_ceiling
