## All Lights
- platform: group
  name: "Dimmable Lights"
  entities:
    - light.living_room_lamp_1
    - light.living_room_lamp_2
    - light.studio_lamp
    - light.kitchen_lamp
    - light.marble_lamp

    # Not plugged in right now
    - light.mans_bedside_lamp
    - light.agnes_bedside_lamp

## Living room
- platform: group
  name: "Living Room Lights"
  entities:
    - light.living_room_lamp_1

## Studio
- platform: group
  name: "Studio Lights"
  entities:
    - light.studio_lamp
    - light.studio_ceiling

## Bedroom
- platform: group
  name: "Bedroom Lights"
  entities:
    - light.living_room_lamp_2
    - light.marble_lamp

## Kitchen
- platform: group
  name: "Kitchen Lights"
  entities:
    - light.kitchen_lamp
