## All Lights
- platform: group
  name: "Dimmable Lights"
  entities:
    - light.living_room_lamp_1
    - light.living_room_lamp_2
    - light.living_room_celling

    - light.studio_lamp
    - light.studio_celling

    - light.mans_bedside_lamp
    - light.agnes_bedside_lamp
    - light.bedroom_celling

    - light.hallway_celling_1
    - light.hallway_celling_2

    - light.kitchen_celling

## Living room
- platform: group
  name: "Living Room Lights"
  entities:
    - light.living_room_lamp_1
    - light.living_room_lamp_2
    - light.living_room_celling

## Studio
- platform: group
  name: "Studio Lights"
  entities:
    - light.studio_lamp
    - light.studio_celling

## Bedroom
- platform: group
  name: "Bedroom Lights"
  entities:
    - light.mans_bedside_lamp
    - light.agnes_bedside_lamp
    - light.bedroom_celling

## Hallway
- platform: group
  name: "Hallway Lights"
  entities:
    - light.hallway_celling_1
    - light.hallway_celling_2

## Kitchen
- platform: group
  name: "Kitchen Lights"
  entities:
    - light.kitchen_celling

## Celling lights
- platform: group
  name: "Celling lights"
  entities:
    - light.kitchen_celling
    - light.hallway_celling_1
    - light.hallway_celling_2
    - light.bedroom_celling
    - light.living_room_celling
    - light.studio_celling
