id: night_time
alias: Night before work
trigger:
  platform: time
  at: "21:00:00"
condition:
  alias: "Atleast one of us is home AND time is 21.00"
  condition: and
  conditions:
    - condition: time
      weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
    - condition: or
      alias: "Atleast one of us is home"
      conditions:
        - condition: state
          entity_id: person.mans
          state: "home"
        - condition: state
          entity_id: person.agnes
          state: "home"
action:
  - alias: Turn of all ceiling lights
    service: light.turn_off
    data:
      entity_id:
        - light.kitchen_ceiling
        - light.hallway_ceiling_1
        - light.hallway_ceiling_2
        - light.bedroom_ceiling
        - light.living_room_ceiling
        - light.studio_ceiling
