id: wakeup
alias: Waking up
trigger:
  platform: time
  at: "06:30:00"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: group.all_persons
      state: "home"
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
action:
  - service: light.turn_on
    data:
      entity_id: light.mans_bedside_lamp
      transition: 1800 # 30 min
      brightness: 70
  - service: light.turn_on
    data:
      entity_id: light.agnes_bedside_lamp
      transition: 1800 # 30 min
      brightness: 70
