id: wakeup
alias: Waking up
trigger:
  platform: template
  value_template: "{{ states('input_text.alarm_time') == states('sensor.time') }}"
condition:
  alias: "Atleast one of us is home AND time is set alarm time"
  condition: and
  conditions:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: or
      alias: "Atleast one of us is home"
      conditions:
        - condition: state
          entity_id: person.mans
          state: "home"
        - condition: state
          entity_id: person.agnes
          state: "home"
action:
  - alias: "Transition Måns Bedside Lamp from 0 => 70"
    service: light.turn_on
    data:
      entity_id: light.mans_bedside_lamp
      transition: 1800 # 30 min
      brightness: 70

  - alias: "Transition Agnes Bedside Lamp from 0 => 70"
    service: light.turn_on
    data:
      entity_id: light.agnes_bedside_lamp
      transition: 1800 # 30 min
      brightness: 70

  - alias: Set volume to 15%
    service: media_player.volume_set
    data_template:
      entity_id:
        - media_player.kitchen_speaker
      volume_level: 0.15

  - alias: Start P1
    service: media_player.play_media
    data_template:
      entity_id: media_player.kitchen_speaker
      media_content_id: http://http-live.sr.se/p1-aac-192
      media_content_type: "audio/mp4"
